---
title: "Template"
output:
  html_document:
    code_folding: hide
  word_document: default
  pdf_document: default
editor_options:
  chunk_output_type: console
---
\def\blue{\color{blue}}


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r parameters}
################ 
##### Data  
#############

################ 
##### Research
################ 

################ 
##### Guess work   
################ 

################ 
#####  Notes:
################ 
### Source ---->  Input ----> Model ----> Policy Estimates (output)
###  (_so)        (_in)       (_mo)        (_pe)
### values      functions   functions      values
###             & values    & values 
### arguments in functions should used "_var" and functions should "_f"

#invisible( list2env(call_params_f(),.GlobalEnv) )

```


# Key policy estimates for policy makers  

```{r final-output}

```

# Methodology

## Main Equation (the model)

\begin{equation}
y = f(x)
\label{eq:1}
\tag{1}
\end{equation}

```{r model}
# - inputs: tax_rev_init_mo, top_tax_base_in
# - outputs: total_rev_pe
```


## Sub components:

### 1 - Component 1 ("$r$")

```{r comp1}
# - inputs: tax_rev_init_mo, top_tax_base_in
# - outputs: total_rev_pe
```
# Main results
```{r main-results}
# - inputs: tax_rev_init_mo, top_tax_base_in
# - outputs: total_rev_pe
```


# Montecarlo simulations  
```{r}
# Draws

# Compute inputs

# Compute model

# Run sims

```

# Sensitivity Analysis  
